export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

export const NEW_PRODUCTS = "NEW_PRODUCTS"
export const NEW_PRODUCTS_SUCCESS = "NEW_PRODUCTS_SUCCESS"
export const NEW_PRODUCTS_FAILURE = " NEW_PRODUCTS_FAILURE"

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE"

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE "

export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const SELECT_PRODUCT_SUCCESS = "SELECT_PRODUCT_SUCCESS";
export const SELECT_PRODUCT_FAILURE = "SELECT_PRODUCT_FAILURE "
